# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'search_by_movies.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(683, 301)
        self.comboBox = QtWidgets.QComboBox(Form)
        self.comboBox.setGeometry(QtCore.QRect(10, 10, 211, 31))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.text_main = QtWidgets.QTextEdit(Form)
        self.text_main.setGeometry(QtCore.QRect(230, 10, 321, 31))
        self.text_main.setObjectName("text_main")
        self.btn = QtWidgets.QPushButton(Form)
        self.btn.setGeometry(QtCore.QRect(560, 10, 111, 31))
        self.btn.setObjectName("btn")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(10, 100, 111, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(10, 140, 161, 21))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(10, 180, 161, 21))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(10, 220, 171, 21))
        self.label_5.setObjectName("label_5")
        self.label_1 = QtWidgets.QLabel(Form)
        self.label_1.setGeometry(QtCore.QRect(10, 60, 81, 21))
        self.label_1.setObjectName("label_1")
        self.label_error = QtWidgets.QLabel(Form)
        self.label_error.setGeometry(QtCore.QRect(10, 260, 251, 31))
        self.label_error.setText("")
        self.label_error.setObjectName("label_error")
        self.textEdit_ID = QtWidgets.QTextEdit(Form)
        self.textEdit_ID.setGeometry(QtCore.QRect(180, 60, 491, 31))
        self.textEdit_ID.setObjectName("textEdit_ID")
        self.textEdit_year = QtWidgets.QTextEdit(Form)
        self.textEdit_year.setGeometry(QtCore.QRect(180, 140, 491, 31))
        self.textEdit_year.setObjectName("textEdit_year")
        self.textEdit_name = QtWidgets.QTextEdit(Form)
        self.textEdit_name.setGeometry(QtCore.QRect(180, 100, 491, 31))
        self.textEdit_name.setObjectName("textEdit_name")
        self.textEdit_genre = QtWidgets.QTextEdit(Form)
        self.textEdit_genre.setGeometry(QtCore.QRect(180, 180, 491, 31))
        self.textEdit_genre.setObjectName("textEdit_genre")
        self.textEdit_duration = QtWidgets.QTextEdit(Form)
        self.textEdit_duration.setGeometry(QtCore.QRect(180, 220, 491, 31))
        self.textEdit_duration.setObjectName("textEdit_duration")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.comboBox.setItemText(0, _translate("Form", "Год выпуска"))
        self.comboBox.setItemText(1, _translate("Form", "Название"))
        self.comboBox.setItemText(2, _translate("Form", "Продолжительность"))
        self.btn.setText(_translate("Form", "Поиск"))
        self.label_2.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt;\">Назавание:</span></p></body></html>"))
        self.label_3.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt;\">Год выпуска:</span></p></body></html>"))
        self.label_4.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt;\">Жанр:</span></p></body></html>"))
        self.label_5.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt;\">Продолжительность:</span></p></body></html>"))
        self.label_1.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt;\">ID:</span></p></body></html>"))
