# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(572, 354)
        self.btn_1 = QtWidgets.QPushButton(Form)
        self.btn_1.setGeometry(QtCore.QRect(10, 60, 231, 31))
        self.btn_1.setObjectName("btn_1")
        self.text_2 = QtWidgets.QTextEdit(Form)
        self.text_2.setGeometry(QtCore.QRect(250, 10, 311, 331))
        self.text_2.setObjectName("text_2")
        self.btn_2 = QtWidgets.QPushButton(Form)
        self.btn_2.setGeometry(QtCore.QRect(10, 110, 231, 31))
        self.btn_2.setObjectName("btn_2")
        self.btn_3 = QtWidgets.QPushButton(Form)
        self.btn_3.setGeometry(QtCore.QRect(10, 160, 231, 31))
        self.btn_3.setObjectName("btn_3")
        self.text_1 = QtWidgets.QTextEdit(Form)
        self.text_1.setGeometry(QtCore.QRect(10, 10, 231, 31))
        self.text_1.setObjectName("text_1")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.btn_1.setText(_translate("Form", "Создать новый"))
        self.btn_2.setText(_translate("Form", "Сохранить файл"))
        self.btn_3.setText(_translate("Form", "Открыть файл"))
