# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'text_flag.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(612, 407)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(20, 20, 161, 61))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(230, 20, 161, 61))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(440, 20, 161, 61))
        self.label_3.setObjectName("label_3")
        self.rdbtn_11 = QtWidgets.QRadioButton(Form)
        self.rdbtn_11.setGeometry(QtCore.QRect(30, 80, 141, 31))
        self.rdbtn_11.setObjectName("rdbtn_11")
        self.group_1 = QtWidgets.QButtonGroup(Form)
        self.group_1.setObjectName("group_1")
        self.group_1.addButton(self.rdbtn_11)
        self.rdbtn_12 = QtWidgets.QRadioButton(Form)
        self.rdbtn_12.setGeometry(QtCore.QRect(30, 120, 141, 31))
        self.rdbtn_12.setObjectName("rdbtn_12")
        self.group_1.addButton(self.rdbtn_12)
        self.rdbtn_13 = QtWidgets.QRadioButton(Form)
        self.rdbtn_13.setGeometry(QtCore.QRect(30, 160, 141, 31))
        self.rdbtn_13.setObjectName("rdbtn_13")
        self.group_1.addButton(self.rdbtn_13)
        self.rdbtn_23 = QtWidgets.QRadioButton(Form)
        self.rdbtn_23.setGeometry(QtCore.QRect(240, 160, 141, 31))
        self.rdbtn_23.setObjectName("rdbtn_23")
        self.group_2 = QtWidgets.QButtonGroup(Form)
        self.group_2.setObjectName("group_2")
        self.group_2.addButton(self.rdbtn_23)
        self.rdbtn_22 = QtWidgets.QRadioButton(Form)
        self.rdbtn_22.setGeometry(QtCore.QRect(240, 120, 141, 31))
        self.rdbtn_22.setObjectName("rdbtn_22")
        self.group_2.addButton(self.rdbtn_22)
        self.rdbtn_21 = QtWidgets.QRadioButton(Form)
        self.rdbtn_21.setGeometry(QtCore.QRect(240, 80, 141, 31))
        self.rdbtn_21.setObjectName("rdbtn_21")
        self.group_2.addButton(self.rdbtn_21)
        self.rdbtn_33 = QtWidgets.QRadioButton(Form)
        self.rdbtn_33.setGeometry(QtCore.QRect(450, 160, 141, 31))
        self.rdbtn_33.setObjectName("rdbtn_33")
        self.group_3 = QtWidgets.QButtonGroup(Form)
        self.group_3.setObjectName("group_3")
        self.group_3.addButton(self.rdbtn_33)
        self.rdbtn_32 = QtWidgets.QRadioButton(Form)
        self.rdbtn_32.setGeometry(QtCore.QRect(450, 120, 141, 31))
        self.rdbtn_32.setObjectName("rdbtn_32")
        self.group_3.addButton(self.rdbtn_32)
        self.rdbtn_31 = QtWidgets.QRadioButton(Form)
        self.rdbtn_31.setGeometry(QtCore.QRect(450, 80, 141, 31))
        self.rdbtn_31.setObjectName("rdbtn_31")
        self.group_3.addButton(self.rdbtn_31)
        self.label_main = QtWidgets.QLabel(Form)
        self.label_main.setGeometry(QtCore.QRect(20, 280, 301, 41))
        self.label_main.setText("")
        self.label_main.setObjectName("label_main")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:22pt;\">Цвет №1</span></p></body></html>"))
        self.label_2.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:22pt;\">Цвет №2</span></p></body></html>"))
        self.label_3.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:22pt;\">Цвет №3</span></p></body></html>"))
        self.rdbtn_11.setText(_translate("Form", "Синий"))
        self.rdbtn_12.setText(_translate("Form", "Красный"))
        self.rdbtn_13.setText(_translate("Form", "Зелёный"))
        self.rdbtn_23.setText(_translate("Form", "Зелёный"))
        self.rdbtn_22.setText(_translate("Form", "Красный"))
        self.rdbtn_21.setText(_translate("Form", "Синий"))
        self.rdbtn_33.setText(_translate("Form", "Зелёный"))
        self.rdbtn_32.setText(_translate("Form", "Красный"))
        self.rdbtn_31.setText(_translate("Form", "Синий"))
